=== jonatanTajada/Recursos-DAM-1--Jonatan/Lenguaje de Marcas/VISUAL_STUDIO/Lenguaje de Marcas_Codigo/PrimerTrimestreXML/Ejercicios_XML/libro.dtd
<!ELEMENT Libro (Titulo, Seccion, SubSeccion?, Contenido, Copyright)>
<!ATTLIST Libro Catalogo ID #REQUIRED>
<!ELEMENT Titulo (#PCDATA)>
<!ELEMENT Seccion (#PCDATA)>
<!ELEMENT SubSeccion (#PCDATA)>
<!ELEMENT Contenido ((Capitulo+)|(Capitulo+, Separacion?)+)>
<!ELEMENT Capitulo (Tema+)>
<!ATTLIST Capitulo materia (XML|XHTML) "XML">
<!ELEMENT Tema (#PCDATA)>
<!ELEMENT Separacion EMPTY>
<!ELEMENT Copyright (#PCDATA)>

=== jonatanTajada/Recursos-DAM-1--Jonatan/Lenguaje de Marcas/VISUAL_STUDIO/Lenguaje de Marcas_Codigo/PrimerTrimestreXML/Ejercicios_XML/libro.xml
<!DOCTYPE Libro SYSTEM "libro.dtd">
<Libro Catalogo="L12345">
    <Titulo>Libro de Ejemplo</Titulo>
    <Seccion>Introducción</Seccion>
    <SubSeccion>Subsección 1</SubSeccion>
    <Contenido>
        <Capitulo materia="XML">
            <Tema>Tema 1.1</Tema>
            <Tema>Tema 1.2</Tema>
        </Capitulo>
        <Capitulo>
            <Tema>Tema 2.1</Tema>
        </Capitulo>
        <Separacion/>
        <Capitulo materia="XHTML">
            <Tema>Tema 3.1</Tema>
            <Tema>Tema 3.2</Tema>
        </Capitulo>
    </Contenido>
    <Copyright>Derechos de autor © 2023</Copyright>
</Libro>
